alg_name: ROME
model_name: Qwen/Qwen2.5-0.5B
layers: [7]
fact_token: subject_last
v_num_grad_steps: 20
v_lr: 0.5
v_loss_layer: 15
clamp_norm_factor: 4
kl_factor: 0.0625
mom2_adjustment: true
rewrite_module_tmp: model.layers.{}.mlp.down_proj
layer_module_tmp: model.layers.{}
mlp_module_tmp: model.layers.{}.mlp
attn_module_tmp: model.layers.{}.self_attn
ln_f_module: model.norm
lm_head_module: lm_head
